title: Glossário CDIC-BR
description: Glossário de termos da Conferência Nacional dos Bispos do Brasil
baseurl: "/glossario"
url: "https://cdic-br.github.io"
repository: cdic-br/glossario

theme: just-the-docs
color_scheme: custom   # <-- aqui você define o esquema de cores customizado
logo: "/assets/CNBB.png"
search_enabled: true
search_placeholder: "Pesquisar Glossário CDIC-BR"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

mermaid:
  version: "9.1.6"

permalink: pretty
heading_anchors: true
aux_links_new_tab: false
nav_enabled: true
nav_sort: none
back_to_top: true
back_to_top_text: "Voltar ao topo"

markdown: kramdown
kramdown
